[package]
name = "rxml"
version = "0.1.0"
authors = ["Radek Szymczyszyn <lavrin@gmail.com>"]

[dependencies]
libc = "*"
erlang_nif-sys = "0.5.3"
RustyXML = { git = "https://github.com/erszcz/RustyXML" }

[lib]
name = "rxml"
crate-type = ["dylib"]
