[package]
name = "rxml"
version = "0.1.0"
authors = ["Radek Szymczyszyn <lavrin@gmail.com>"]

[dependencies]
libc = "*"
ruster_unsafe = "0.2.0"
RustyXML = "*"

[lib]
name = "rxml"
crate-type = ["dylib"]
